//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileHandler.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileHandler.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΙΛΙΑΔΟΣ Α
        ///
        ///   Μη̃νιν ἄειδε θεὰ Πηληϊάδεω &apos;Αχιλη̃ος
        ///οὐλομένην, ἣ μυρί&apos; &apos;Αχαιοι̃ς ἄλγε&apos; ἔθηκε,
        ///πολλὰς δ&apos; ἰφθίμους ψυχὰς &apos;Άϊδι προΐαψεν
        ///ἡρώων, αὐτοὺς δὲ ἑλώρια τευ̃χε κύνεσσιν
        ///οἰωνοι̃σί τε πα̃σι, Διὸς δ&apos; ἐτελείετο βουλή,
        ///ἐξ οὑ̃ δὴ τὰ πρω̃τα διαστήτην ἐρίσαντε
        ///&apos;Ατρεΐδης τε ἄναξ ἀνδρω̃ν καὶ δι̃ος &apos;Αχιλλεύσ.
        ///   Τίς τάρ σφωε θεω̃ν ἔριδι ξυνέηκε μάχεσθαι;
        ///Λητου̃ς καὶ Διὸς υἱόσ: ὃ γὰρ βασιλη̃ϊ χολωθεὶς
        ///νου̃σον ἀνὰ στρατὸν ὄρσε κακήν, ὀλέκοντο δὲ λαοί,
        ///οὕν [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
    }
}
